language: generic
sudo: required
services:
    - docker
  
before_install:
    - docker build -t fibonacci-frontend-test -f ./frontend/Dockerfile.dev ./frontend
  
script:
    - docker run -e CI=true fibonacci-frontend-test npm run test -- --coverage

after_success:
    - docker build -t masterweb87/fibonacci-frontend ./frontend
    - docker build -t masterweb87/fibonacci-nginx ./nginx
    - docker build -t masterweb87/fibonacci-server ./server
    - docker build -t masterweb87/fibonacci-worker ./worker
    # Login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push the images to Docker Hub
    - docker push masterweb87/fibonacci-frontend
    - docker push masterweb87/fibonacci-nginx
    - docker push masterweb87/fibonacci-server
    - docker push masterweb87/fibonacci-worker
    
deploy:
    edge: true 
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "fibonacci-docker"
    env: "FibonacciDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-375702630848"
    bucket_path: "fibonacci-multi-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY